### ISSUE TITLE
Payment selection is not working

### ISSUE THREAD

**Issue by lmeyer1** [lmeyer1/prestashop-1.6#3]
**Describe the bug**
When placing an order on Prestashop with Postfinance Checkout, the display of the page is not coherent, there are two buttons labelled `I confirm my order`, that do not have the same effect.
Additionally either of both button confirms the order.

**To Reproduce**
1. Open the shop with Chrome
1. Add a product to the cart
2. Place the order, on step `5. Paiement`, choose `Carte Postfinance`
3. Notice the strange display with the two buttons
4. Hit `F12` to open Chrome Dev Console
5. Click on the first button
6. Note the error in the Dev console

        checkout.js:90 Uncaught TypeError: Cannot read properties of undefined (reading 'processing')
        at HTMLButtonElement.handler_submit (checkout.js:90:22)
        at HTMLButtonElement.dispatch (jquery-1.11.0.min.js:3:8066)
        at HTMLButtonElement.r.handle (jquery-1.11.0.min.js:3:4767)

7. Click on the second button
8. An empty page displays, with an error in Dev console
![2022-01-28_152409](https://user-images.githubusercontent.com/7520695/151563551-329859fd-04c4-4803-b11b-787b17cf2a7f.jpg)
![2022-01-28_152420](https://user-images.githubusercontent.com/7520695/151563596-87c74fe6-c348-42cd-883e-a083fc6799fa.jpg)

**Expected behavior**
We should be able to place an order.

**Screenshots**
There are two buttons `I confirm my order`
![2022-01-28_152117](https://user-images.githubusercontent.com/7520695/151563002-a7e46eec-3d5a-44c8-adbc-277375dc2063.jpg)

**Software versions (please complete the following information):**
 - Prestashop: 1.6.1.24, fresh install, default demo data.
 - Postfinance Checkout: 1.2.17, latest version as of today
 - PHP: 7.1.32

**Additional Info**

The offending lines in file `views/js/frontend/checkout.js` are:

        handler_submit : function (event) {
            if(!self.processing) {
                var self = event.data.self;
                self.disable_pay_button();

Obviously `var self = event.data.self;` should preceed `if(!self.processing) {`

**Comment by lmeyer1** [comment]
Close in favor of https://github.com/pfpayments/prestashop-1.6/issues/5
